-- V1.11: Remove unique constraint on email column
-- Allows multiple users to share the same email address in certain circumstances

-- Drop the unique constraint on email (constraint name auto-generated by Hibernate)
-- PostgreSQL syntax
ALTER TABLE users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;

-- Also try common Hibernate-generated constraint name patterns
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;
ALTER TABLE users DROP CONSTRAINT IF EXISTS uk_users_email;

-- For H2 database (development), drop the unique index if it exists
DROP INDEX IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
