-- Service account tokens become revocable: each issued JWT carries a jti that
-- maps to a row here. Revocation sets revoked_at; JwtAuthenticationFilter
-- refuses any service-account token whose row is missing or revoked.
--
-- No token value or hash is stored. The JWT signature proves authenticity;
-- this table only supplies identity, revocation state, and display metadata.

CREATE TABLE IF NOT EXISTS service_account_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_name varchar(255) NOT NULL,
    jti varchar(36) NOT NULL,
    global_role varchar(50),
    org_role varchar(50),
    organization_id bigint,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    revoked_by varchar(255),
    created_at timestamp(6) without time zone NOT NULL DEFAULT now(),
    last_used_at timestamp(6) without time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_service_account_tokens_jti
    ON service_account_tokens (jti);

CREATE INDEX IF NOT EXISTS idx_service_account_tokens_user
    ON service_account_tokens (user_id);
