--
-- Drift catch-up: bring any DB up to V1.0__baseline.sql state.
--
-- Generated mechanically from V1.0__baseline.sql by tools/v12_gen.py.
-- Existing prod DBs that ran with ddl-auto=update before the Flyway switch
-- are missing tables added to entities AFTER their last successful Hibernate
-- auto-update but BEFORE V1.0 was generated. The fail-fast ddl-auto=validate
-- mode then refuses to start the app.
--
-- Strategy:
--   * CREATE TABLE IF NOT EXISTS — no-op on existing, creates missing.
--   * Identity + primary keys inlined so missing tables are fully usable.
--   * CREATE INDEX IF NOT EXISTS — idempotent.
--   * FK and UNIQUE constraints wrapped in DO blocks that check
--     pg_constraint.conname before adding — no-op if already present.
--
-- This migration is intentionally large (~1500 lines). It's a one-shot
-- reconciliation; future schema changes go in V1.13+.

-- ============================================================
-- Tables (with inline identity + primary key)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ai_sessions (
    id uuid NOT NULL,
    ended_at timestamp(6) without time zone,
    error_code character varying(64),
    error_message text,
    input_summary text,
    mode character varying(16) NOT NULL,
    model character varying(64) NOT NULL,
    organization_id bigint NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    tokens_in integer NOT NULL,
    tokens_out integer NOT NULL,
    user_id bigint NOT NULL,
    wizard_kind character varying(32) NOT NULL,
    events_json text,
    cost_usd_micros bigint DEFAULT 0 NOT NULL,
    CONSTRAINT ai_sessions_mode_check CHECK (((mode)::text = ANY ((ARRAY['STREAMING'::character varying, 'THOROUGH'::character varying])::text[]))),
    CONSTRAINT ai_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'AWAITING_INPUT'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT ai_sessions_wizard_kind_check CHECK (((wizard_kind)::text = ANY ((ARRAY['SMOKE'::character varying, 'CATALOG'::character varying, 'PROFILE'::character varying, 'COMPONENT_DEF'::character varying, 'SSP'::character varying, 'POAM'::character varying, 'BUILDER_ASSIST'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.artifact_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_id character varying(100) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    artifact_id bigint NOT NULL,
    parent_comment_id bigint,
    user_id bigint NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.artifact_ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    rating integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    artifact_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT artifact_ratings_rating_check CHECK (((rating <= 5) AND (rating >= 1))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.artifact_tag_mapping (
    artifact_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    PRIMARY KEY (artifact_id, tag_id));

CREATE TABLE IF NOT EXISTS public.artifact_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description character varying(500),
    name character varying(100) NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.artifact_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    change_description character varying(1000),
    content_size bigint NOT NULL,
    description_snapshot character varying(2000),
    extracted_variables_snapshot text,
    file_path character varying(500) NOT NULL,
    title_snapshot character varying(255),
    uploaded_at timestamp(6) without time zone NOT NULL,
    version_id character varying(100) NOT NULL,
    version_number integer NOT NULL,
    visibility_snapshot character varying(20),
    artifact_id bigint NOT NULL,
    uploaded_by bigint NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.artifacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    artifact_id character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(2000),
    download_count bigint NOT NULL,
    extracted_variables text,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    view_count bigint NOT NULL,
    visibility character varying(20) NOT NULL,
    created_by bigint NOT NULL,
    current_version_id bigint,
    organization_id bigint,
    CONSTRAINT artifacts_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PRIVATE'::character varying, 'ORGANIZATION'::character varying, 'PUBLIC'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action character varying(50),
    category character varying(50) NOT NULL,
    error_message character varying(1000),
    event_type character varying(50) NOT NULL,
    ip_address character varying(45),
    metadata text,
    outcome character varying(20) NOT NULL,
    processing_time_ms bigint,
    resource character varying(500),
    review_notes character varying(1000),
    reviewed boolean,
    reviewed_at timestamp(6) without time zone,
    reviewed_by character varying(100),
    risk_level character varying(10),
    session_id character varying(100),
    "timestamp" timestamp(6) without time zone NOT NULL,
    user_agent character varying(500),
    user_id bigint,
    username character varying(100),
    http_method character varying(10),
    integrity_hash character varying(64),
    previous_hash character varying(64),
    request_url character varying(2000),
    CONSTRAINT audit_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['AUTH_REGISTER_SUCCESS'::character varying, 'AUTH_REGISTER_FAILURE'::character varying, 'AUTH_LOGIN_SUCCESS'::character varying, 'AUTH_LOGIN_FAILURE'::character varying, 'AUTH_LOGOUT'::character varying, 'AUTH_TOKEN_REFRESH'::character varying, 'AUTH_SERVICE_TOKEN_GENERATED'::character varying, 'AUTH_ORG_SELECTION'::character varying, 'AUTHZ_ACCESS_DENIED'::character varying, 'AUTHZ_ACCESS_GRANTED'::character varying, 'AUTHZ_PERMISSION_CHANGED'::character varying, 'DATA_FILE_UPLOAD'::character varying, 'DATA_FILE_ACCESS'::character varying, 'DATA_FILE_DELETE'::character varying, 'DATA_FILE_MODIFY'::character varying, 'DATA_VALIDATION'::character varying, 'DATA_CONVERSION'::character varying, 'DATA_PROFILE_RESOLVE'::character varying, 'CONFIG_PROFILE_UPDATE'::character varying, 'CONFIG_PASSWORD_CHANGE'::character varying, 'CONFIG_LOGO_UPLOAD'::character varying, 'CONFIG_SYSTEM_CHANGE'::character varying, 'SECURITY_ACCOUNT_LOCKED'::character varying, 'SECURITY_ACCOUNT_UNLOCKED'::character varying, 'SECURITY_IP_BLOCKED'::character varying, 'SECURITY_PASSWORD_RESET_REQUEST'::character varying, 'SECURITY_PASSWORD_RESET_COMPLETE'::character varying, 'SECURITY_SUSPICIOUS_ACTIVITY'::character varying, 'SECURITY_RATE_LIMIT_EXCEEDED'::character varying, 'SECURITY_INVALID_FILE_UPLOAD'::character varying, 'SYSTEM_STARTUP'::character varying, 'SYSTEM_SHUTDOWN'::character varying, 'SYSTEM_ERROR'::character varying, 'SYSTEM_DATABASE_ERROR'::character varying, 'SYSTEM_EXTERNAL_API_ERROR'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.authorization_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    last_updated_at timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    created_by bigint NOT NULL,
    last_updated_by bigint,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.authorization_variables (
    authorization_id bigint NOT NULL,
    variable_value text,
    variable_name character varying(255) NOT NULL,
    PRIMARY KEY (authorization_id, variable_name));

CREATE TABLE IF NOT EXISTS public.authorizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authorized_at timestamp(6) without time zone NOT NULL,
    authorizing_official character varying(255),
    certificate_issuer character varying(500),
    certificate_not_after timestamp(6) without time zone,
    certificate_not_before timestamp(6) without time zone,
    certificate_serial character varying(100),
    certificate_verification_date timestamp(6) without time zone,
    certificate_verification_notes text,
    certificate_verified boolean,
    completed_content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_authorized date,
    date_expired date,
    digital_signature_method character varying(50),
    document_hash character varying(64),
    name character varying(255) NOT NULL,
    sar_item_id character varying(100),
    security_manager character varying(255),
    signature_timestamp timestamp(6) without time zone,
    signer_certificate text,
    signer_common_name character varying(255),
    signer_edipi character varying(10),
    signer_email character varying(255),
    ssp_item_id character varying(100) NOT NULL,
    system_owner character varying(255),
    authorized_by bigint NOT NULL,
    template_id bigint NOT NULL,
    electronic_signature_image text,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.catalogs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    control_count integer,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    file_size bigint,
    filename character varying(255) NOT NULL,
    group_count integer,
    oscal_uuid character varying(255) NOT NULL,
    oscal_version character varying(20),
    param_count integer,
    storage_path character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    version character varying(50),
    created_by bigint NOT NULL,
    last_updated_by bigint,
    is_draft boolean DEFAULT false NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.component_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    capability_count integer,
    component_count integer,
    control_count integer,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    file_size bigint,
    filename character varying(255) NOT NULL,
    oscal_uuid character varying(255) NOT NULL,
    oscal_version character varying(20),
    storage_path character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    version character varying(50),
    created_by bigint NOT NULL,
    last_updated_by bigint,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.conditions_of_approval (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    condition text NOT NULL,
    condition_type character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    due_date date,
    updated_at timestamp(6) without time zone,
    authorization_id bigint NOT NULL,
    CONSTRAINT conditions_of_approval_condition_type_check CHECK (((condition_type)::text = ANY ((ARRAY['MANDATORY'::character varying, 'RECOMMENDED'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.custom_validation_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    applicable_model_types character varying(500),
    category character varying(500),
    constraint_details character varying(1000),
    created_by character varying(100),
    created_date timestamp(6) without time zone NOT NULL,
    description character varying(1000),
    enabled boolean NOT NULL,
    field_path character varying(500),
    name character varying(255) NOT NULL,
    rule_expression character varying(2000),
    rule_id character varying(100) NOT NULL,
    rule_type character varying(50) NOT NULL,
    severity character varying(20) NOT NULL,
    updated_date timestamp(6) without time zone NOT NULL,
    user_id bigint,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.invitations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    accepted_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    role character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    token character varying(64) NOT NULL,
    accepted_by_user_id bigint,
    invited_by_user_id bigint NOT NULL,
    organization_id bigint NOT NULL,
    CONSTRAINT invitations_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ORG_ADMIN'::character varying])::text[]))),
    CONSTRAINT invitations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REVOKED'::character varying, 'EXPIRED'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.library_item_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_id character varying(100) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    library_item_id bigint NOT NULL,
    parent_comment_id bigint,
    user_id bigint NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.library_item_ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    rating integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    library_item_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT library_item_ratings_rating_check CHECK (((rating <= 5) AND (rating >= 1))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.library_item_tags (
    library_item_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    PRIMARY KEY (library_item_id, tag_id));

CREATE TABLE IF NOT EXISTS public.library_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(2000),
    download_count bigint NOT NULL,
    item_id character varying(100) NOT NULL,
    oscal_type character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    view_count bigint NOT NULL,
    created_by bigint NOT NULL,
    current_version_id bigint,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.library_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description character varying(500),
    name character varying(100) NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.library_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    change_description character varying(1000),
    description_snapshot character varying(2000),
    file_name character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_size bigint NOT NULL,
    format character varying(20) NOT NULL,
    oscal_type_snapshot character varying(50),
    title_snapshot character varying(255),
    uploaded_at timestamp(6) without time zone NOT NULL,
    version_id character varying(100) NOT NULL,
    version_number integer NOT NULL,
    library_item_id bigint NOT NULL,
    uploaded_by bigint NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.mfa_backup_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_hash character varying(64) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    used boolean NOT NULL,
    used_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.operation_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_operation_id character varying(100),
    details character varying(1000),
    duration_ms bigint,
    file_count integer,
    file_name character varying(255) NOT NULL,
    format character varying(20),
    model_type character varying(50),
    operation_type character varying(50) NOT NULL,
    success boolean NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    user_id bigint,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.org_ai_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    anthropic_key_encrypted text,
    anthropic_key_fingerprint character varying(32),
    created_at timestamp(6) without time zone NOT NULL,
    default_model character varying(64) NOT NULL,
    enabled boolean NOT NULL,
    organization_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.organization_memberships (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    role character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    organization_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT organization_memberships_role_check CHECK (((role)::text = ANY ((ARRAY['ORG_ADMIN'::character varying, 'USER'::character varying])::text[]))),
    CONSTRAINT organization_memberships_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LOCKED'::character varying, 'DEACTIVATED'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    logo_url character varying(500),
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.oscal_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    is_draft boolean NOT NULL,
    file_size bigint,
    filename character varying(255) NOT NULL,
    model_type character varying(40) NOT NULL,
    oscal_uuid character varying(255) NOT NULL,
    oscal_version character varying(20),
    stats_json text,
    storage_path character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    version character varying(50),
    created_by bigint NOT NULL,
    last_updated_by bigint,
    CONSTRAINT oscal_documents_model_type_check CHECK (((model_type)::text = ANY ((ARRAY['SYSTEM_SECURITY_PLAN'::character varying, 'ASSESSMENT_PLAN'::character varying, 'ASSESSMENT_RESULTS'::character varying, 'PLAN_OF_ACTION_AND_MILESTONES'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alter_count integer,
    control_count integer,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    file_size bigint,
    filename character varying(255) NOT NULL,
    import_count integer,
    oscal_uuid character varying(255) NOT NULL,
    oscal_version character varying(20),
    storage_path character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    version character varying(50),
    created_by bigint NOT NULL,
    last_updated_by bigint,
    is_draft boolean NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.reusable_elements (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    is_shared boolean,
    json_content text NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone,
    use_count integer,
    created_by bigint NOT NULL,
    CONSTRAINT reusable_elements_type_check CHECK (((type)::text = ANY ((ARRAY['ROLE'::character varying, 'PARTY'::character varying, 'LINK'::character varying, 'BACK_MATTER'::character varying, 'RESPONSIBLE_PARTY'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.saved_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_id character varying(100) NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_size bigint NOT NULL,
    format character varying(20) NOT NULL,
    model_type character varying(50) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.security_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    audit_log_retention_days integer NOT NULL,
    mfa_required boolean NOT NULL,
    password_max_length integer NOT NULL,
    password_min_length integer NOT NULL,
    password_rotation_days integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.user_access_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email character varying(255),
    first_name character varying(100),
    last_name character varying(100),
    message text,
    notes text,
    request_date timestamp(6) without time zone NOT NULL,
    reviewed_date timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    username character varying(100),
    organization_id bigint NOT NULL,
    reviewed_by bigint,
    user_id bigint,
    CONSTRAINT user_access_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id bigint NOT NULL,
    role character varying(255)
);

CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_locked_until timestamp(6) without time zone,
    city character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    failed_login_attempts integer,
    first_name character varying(100),
    global_role character varying(20) NOT NULL,
    last_failed_login timestamp(6) without time zone,
    last_failed_login_ip character varying(45),
    last_login timestamp(6) without time zone,
    last_name character varying(100),
    logo text,
    must_change_password boolean NOT NULL,
    organization character varying(255),
    password character varying(255) NOT NULL,
    password_changed_at timestamp(6) without time zone,
    phone_number character varying(20),
    state character varying(50),
    street character varying(255),
    title character varying(100),
    username character varying(100) NOT NULL,
    zip character varying(20),
    mfa_secret character varying(512),
    mfa_enabled boolean DEFAULT false,
    mfa_setup_completed boolean DEFAULT false,
    CONSTRAINT users_global_role_check CHECK (((global_role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'USER'::character varying])::text[]))),
    PRIMARY KEY (id));

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_audit_event_type ON public.audit_events USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_audit_ip_address ON public.audit_events USING btree (ip_address);
CREATE INDEX IF NOT EXISTS idx_audit_outcome ON public.audit_events USING btree (outcome);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON public.audit_events USING btree ("timestamp");
CREATE INDEX IF NOT EXISTS idx_audit_username ON public.audit_events USING btree (username);
CREATE INDEX IF NOT EXISTS idx_backup_codes_hash ON public.mfa_backup_codes USING btree (code_hash);
CREATE INDEX IF NOT EXISTS idx_backup_codes_user_id ON public.mfa_backup_codes USING btree (user_id);

-- ============================================================
-- Unique constraints (idempotent via pg_constraint check)
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk1pccrf8icu1vsxnglf0l0u3vy'
  ) THEN
    ALTER TABLE public.artifact_tags ADD CONSTRAINT uk1pccrf8icu1vsxnglf0l0u3vy UNIQUE (name);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk3qfowp62qlf549o7y3f9j99d'
  ) THEN
    ALTER TABLE public.artifact_ratings ADD CONSTRAINT uk3qfowp62qlf549o7y3f9j99d UNIQUE (artifact_id, user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk3ugnqgfrbl46r9366agnhdw78'
  ) THEN
    ALTER TABLE public.library_items ADD CONSTRAINT uk3ugnqgfrbl46r9366agnhdw78 UNIQUE (current_version_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk4ri8glv86m520pn3boe318se5'
  ) THEN
    ALTER TABLE public.artifact_versions ADD CONSTRAINT uk4ri8glv86m520pn3boe318se5 UNIQUE (version_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk53hqprnq1jmqyydhcd53jyu6k'
  ) THEN
    ALTER TABLE public.component_definitions ADD CONSTRAINT uk53hqprnq1jmqyydhcd53jyu6k UNIQUE (oscal_uuid);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk5jvx6g2cja4mnwgxisqqj99ys'
  ) THEN
    ALTER TABLE public.library_versions ADD CONSTRAINT uk5jvx6g2cja4mnwgxisqqj99ys UNIQUE (version_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk5pf0oql3oy5ty8p2diejff8l6'
  ) THEN
    ALTER TABLE public.artifacts ADD CONSTRAINT uk5pf0oql3oy5ty8p2diejff8l6 UNIQUE (artifact_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk5r54uotuyyfijedlydeocoevw'
  ) THEN
    ALTER TABLE public.saved_files ADD CONSTRAINT uk5r54uotuyyfijedlydeocoevw UNIQUE (file_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uk60cfslnfae3fptd5mxokwvwr8'
  ) THEN
    ALTER TABLE public.org_ai_settings ADD CONSTRAINT uk60cfslnfae3fptd5mxokwvwr8 UNIQUE (organization_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukaok26sct34b3rc3lo7mfqmksi'
  ) THEN
    ALTER TABLE public.organization_memberships ADD CONSTRAINT ukaok26sct34b3rc3lo7mfqmksi UNIQUE (user_id, organization_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukcmf036a7r76x28o5ecm1simno'
  ) THEN
    ALTER TABLE public.artifacts ADD CONSTRAINT ukcmf036a7r76x28o5ecm1simno UNIQUE (current_version_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukftvos7nh59fychw07o4cuu07b'
  ) THEN
    ALTER TABLE public.artifact_comments ADD CONSTRAINT ukftvos7nh59fychw07o4cuu07b UNIQUE (comment_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukgp0pwe1d6gp0u7to14h1rbtow'
  ) THEN
    ALTER TABLE public.oscal_documents ADD CONSTRAINT ukgp0pwe1d6gp0u7to14h1rbtow UNIQUE (oscal_uuid);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukgqj86qwp8u9c9s0fqt2lrocn6'
  ) THEN
    ALTER TABLE public.custom_validation_rules ADD CONSTRAINT ukgqj86qwp8u9c9s0fqt2lrocn6 UNIQUE (rule_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukhm8wvdo8igpjnq3fw32yjnabd'
  ) THEN
    ALTER TABLE public.catalogs ADD CONSTRAINT ukhm8wvdo8igpjnq3fw32yjnabd UNIQUE (oscal_uuid);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukhsjjya2g9cu0esiqbxue0otnb'
  ) THEN
    ALTER TABLE public.library_item_comments ADD CONSTRAINT ukhsjjya2g9cu0esiqbxue0otnb UNIQUE (comment_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uklsnrxgjsnopf3cqxw93bt4nvx'
  ) THEN
    ALTER TABLE public.library_tags ADD CONSTRAINT uklsnrxgjsnopf3cqxw93bt4nvx UNIQUE (name);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukn3ca5wlpc9tushnes3tojrjd'
  ) THEN
    ALTER TABLE public.profiles ADD CONSTRAINT ukn3ca5wlpc9tushnes3tojrjd UNIQUE (oscal_uuid);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uknp93i7j24lbrbi7nibdu8a295'
  ) THEN
    ALTER TABLE public.library_items ADD CONSTRAINT uknp93i7j24lbrbi7nibdu8a295 UNIQUE (item_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukp69ogdrhuvt59vhl09i4xyku6'
  ) THEN
    ALTER TABLE public.library_item_ratings ADD CONSTRAINT ukp69ogdrhuvt59vhl09i4xyku6 UNIQUE (library_item_id, user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukp9pbw3flq9hkay8hdx3ypsldy'
  ) THEN
    ALTER TABLE public.organizations ADD CONSTRAINT ukp9pbw3flq9hkay8hdx3ypsldy UNIQUE (name);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukr43af9ap4edm43mmtq01oddj6'
  ) THEN
    ALTER TABLE public.users ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ukt4i6esv44p6yi7cxq277vlo3i'
  ) THEN
    ALTER TABLE public.invitations ADD CONSTRAINT ukt4i6esv44p6yi7cxq277vlo3i UNIQUE (token);
  END IF;
END $$;

-- ============================================================
-- Foreign keys (idempotent via pg_constraint check)
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk1gycw02eeuio8qbtve6ff1jad'
  ) THEN
    ALTER TABLE public.reusable_elements
      ADD CONSTRAINT fk1gycw02eeuio8qbtve6ff1jad FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk1iuo7iuykker01wt7gj3j2krs'
  ) THEN
    ALTER TABLE public.custom_validation_rules
      ADD CONSTRAINT fk1iuo7iuykker01wt7gj3j2krs FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk1rsowbejrbs49fgoxofmku7hb'
  ) THEN
    ALTER TABLE public.user_access_requests
      ADD CONSTRAINT fk1rsowbejrbs49fgoxofmku7hb FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk2hry9fy70edjxpajxgd8nwjra'
  ) THEN
    ALTER TABLE public.library_versions
      ADD CONSTRAINT fk2hry9fy70edjxpajxgd8nwjra FOREIGN KEY (library_item_id)
      REFERENCES public.library_items(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk2o39jpg4nxk694dpxwgosp08r'
  ) THEN
    ALTER TABLE public.organization_memberships
      ADD CONSTRAINT fk2o39jpg4nxk694dpxwgosp08r FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk328rxr20qvmimumv0pmsxhgbj'
  ) THEN
    ALTER TABLE public.user_access_requests
      ADD CONSTRAINT fk328rxr20qvmimumv0pmsxhgbj FOREIGN KEY (reviewed_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk3uyim84uifo49fl2uudl8gmd3'
  ) THEN
    ALTER TABLE public.oscal_documents
      ADD CONSTRAINT fk3uyim84uifo49fl2uudl8gmd3 FOREIGN KEY (last_updated_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk4kn302ss3qq0h9ponuaolbxd2'
  ) THEN
    ALTER TABLE public.artifact_ratings
      ADD CONSTRAINT fk4kn302ss3qq0h9ponuaolbxd2 FOREIGN KEY (artifact_id)
      REFERENCES public.artifacts(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk4varegmiee472yiy8t4m5m6yk'
  ) THEN
    ALTER TABLE public.artifacts
      ADD CONSTRAINT fk4varegmiee472yiy8t4m5m6yk FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk640j9wf96181ktxr70xtf2ghi'
  ) THEN
    ALTER TABLE public.library_items
      ADD CONSTRAINT fk640j9wf96181ktxr70xtf2ghi FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk7b5qiflc1cwpe6a5016c9fdxf'
  ) THEN
    ALTER TABLE public.authorization_templates
      ADD CONSTRAINT fk7b5qiflc1cwpe6a5016c9fdxf FOREIGN KEY (last_updated_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk7fasv4x02f7j333a940jkdjcr'
  ) THEN
    ALTER TABLE public.authorization_templates
      ADD CONSTRAINT fk7fasv4x02f7j333a940jkdjcr FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk8iuqgdfox5xnnx4f3y7gbo935'
  ) THEN
    ALTER TABLE public.saved_files
      ADD CONSTRAINT fk8iuqgdfox5xnnx4f3y7gbo935 FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk8l8s35o1br9q0qcq8asxgs8ul'
  ) THEN
    ALTER TABLE public.operation_history
      ADD CONSTRAINT fk8l8s35o1br9q0qcq8asxgs8ul FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk95roqacmu38ve113h225alk1g'
  ) THEN
    ALTER TABLE public.library_item_tags
      ADD CONSTRAINT fk95roqacmu38ve113h225alk1g FOREIGN KEY (library_item_id)
      REFERENCES public.library_items(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk9b0jm0vj29bwx249h11w35nwu'
  ) THEN
    ALTER TABLE public.library_versions
      ADD CONSTRAINT fk9b0jm0vj29bwx249h11w35nwu FOREIGN KEY (uploaded_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fka03c2i4yk5mhav52irjbop0u2'
  ) THEN
    ALTER TABLE public.artifacts
      ADD CONSTRAINT fka03c2i4yk5mhav52irjbop0u2 FOREIGN KEY (current_version_id)
      REFERENCES public.artifact_versions(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkagg5nmf6k21nnhyfsl72lcq2y'
  ) THEN
    ALTER TABLE public.invitations
      ADD CONSTRAINT fkagg5nmf6k21nnhyfsl72lcq2y FOREIGN KEY (invited_by_user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkbdso6o6s634gtcawdxejwibiy'
  ) THEN
    ALTER TABLE public.library_items
      ADD CONSTRAINT fkbdso6o6s634gtcawdxejwibiy FOREIGN KEY (current_version_id)
      REFERENCES public.library_versions(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkbfuxv4vjy7qc00vglp7rd978e'
  ) THEN
    ALTER TABLE public.artifact_tag_mapping
      ADD CONSTRAINT fkbfuxv4vjy7qc00vglp7rd978e FOREIGN KEY (artifact_id)
      REFERENCES public.artifacts(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkcynxctc6sock0y3lsi2yj8p3'
  ) THEN
    ALTER TABLE public.library_item_comments
      ADD CONSTRAINT fkcynxctc6sock0y3lsi2yj8p3 FOREIGN KEY (parent_comment_id)
      REFERENCES public.library_item_comments(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkdp7o1el5nau32ipwghw7hfvsp'
  ) THEN
    ALTER TABLE public.library_item_comments
      ADD CONSTRAINT fkdp7o1el5nau32ipwghw7hfvsp FOREIGN KEY (library_item_id)
      REFERENCES public.library_items(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkedfr2sj5wsdjnrnwylkari8c2'
  ) THEN
    ALTER TABLE public.organization_memberships
      ADD CONSTRAINT fkedfr2sj5wsdjnrnwylkari8c2 FOREIGN KEY (organization_id)
      REFERENCES public.organizations(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkeehl8k0os34tkf0qs5xna5lik'
  ) THEN
    ALTER TABLE public.library_item_ratings
      ADD CONSTRAINT fkeehl8k0os34tkf0qs5xna5lik FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkefirrbyf52hq99918waakgtwh'
  ) THEN
    ALTER TABLE public.profiles
      ADD CONSTRAINT fkefirrbyf52hq99918waakgtwh FOREIGN KEY (last_updated_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkffox42gadkbkvb4clocxt2k3q'
  ) THEN
    ALTER TABLE public.user_access_requests
      ADD CONSTRAINT fkffox42gadkbkvb4clocxt2k3q FOREIGN KEY (organization_id)
      REFERENCES public.organizations(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkhbffs1oebaxvyl7an4ybwsbsj'
  ) THEN
    ALTER TABLE public.invitations
      ADD CONSTRAINT fkhbffs1oebaxvyl7an4ybwsbsj FOREIGN KEY (accepted_by_user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkhfh9dx7w3ubf1co1vdev94g3f'
  ) THEN
    ALTER TABLE public.user_roles
      ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkhfjh5vaec4el5vkeadv15u8fr'
  ) THEN
    ALTER TABLE public.artifact_comments
      ADD CONSTRAINT fkhfjh5vaec4el5vkeadv15u8fr FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkhynqwmmb7w3j2j68792y85xi8'
  ) THEN
    ALTER TABLE public.artifacts
      ADD CONSTRAINT fkhynqwmmb7w3j2j68792y85xi8 FOREIGN KEY (organization_id)
      REFERENCES public.organizations(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkiaff94dptc6thrqcc7lup4f68'
  ) THEN
    ALTER TABLE public.profiles
      ADD CONSTRAINT fkiaff94dptc6thrqcc7lup4f68 FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkiw0epmifd07dpr2q69wut1naw'
  ) THEN
    ALTER TABLE public.conditions_of_approval
      ADD CONSTRAINT fkiw0epmifd07dpr2q69wut1naw FOREIGN KEY (authorization_id)
      REFERENCES public.authorizations(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkjhvnd351ldv22dw88glctnaiy'
  ) THEN
    ALTER TABLE public.artifact_comments
      ADD CONSTRAINT fkjhvnd351ldv22dw88glctnaiy FOREIGN KEY (parent_comment_id)
      REFERENCES public.artifact_comments(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkk69oefpvkw75ov346moe7mgq8'
  ) THEN
    ALTER TABLE public.artifact_comments
      ADD CONSTRAINT fkk69oefpvkw75ov346moe7mgq8 FOREIGN KEY (artifact_id)
      REFERENCES public.artifacts(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkkkdyfx8aro1i33d2modkovbp7'
  ) THEN
    ALTER TABLE public.artifact_tag_mapping
      ADD CONSTRAINT fkkkdyfx8aro1i33d2modkovbp7 FOREIGN KEY (tag_id)
      REFERENCES public.artifact_tags(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkldd3n6q1i8u05tvrde1dckds0'
  ) THEN
    ALTER TABLE public.library_item_comments
      ADD CONSTRAINT fkldd3n6q1i8u05tvrde1dckds0 FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fklmjiqb7syb3ux9rqj5ttn86r1'
  ) THEN
    ALTER TABLE public.artifact_ratings
      ADD CONSTRAINT fklmjiqb7syb3ux9rqj5ttn86r1 FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkmkiqhhl3lxfsihr0139oxrqrm'
  ) THEN
    ALTER TABLE public.authorizations
      ADD CONSTRAINT fkmkiqhhl3lxfsihr0139oxrqrm FOREIGN KEY (authorized_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkmw500nxtn74f0l14qqv1assil'
  ) THEN
    ALTER TABLE public.authorization_variables
      ADD CONSTRAINT fkmw500nxtn74f0l14qqv1assil FOREIGN KEY (authorization_id)
      REFERENCES public.authorizations(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkmwjh90v56s0wv2230hc3nls5l'
  ) THEN
    ALTER TABLE public.catalogs
      ADD CONSTRAINT fkmwjh90v56s0wv2230hc3nls5l FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkofwmkg7ykl4crooo6wckqh6ds'
  ) THEN
    ALTER TABLE public.authorizations
      ADD CONSTRAINT fkofwmkg7ykl4crooo6wckqh6ds FOREIGN KEY (template_id)
      REFERENCES public.authorization_templates(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkotblq6fvgt9yqk8c21hr02cov'
  ) THEN
    ALTER TABLE public.library_item_ratings
      ADD CONSTRAINT fkotblq6fvgt9yqk8c21hr02cov FOREIGN KEY (library_item_id)
      REFERENCES public.library_items(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkovsacjon7ac5t8f8ey4k6bdjp'
  ) THEN
    ALTER TABLE public.library_item_tags
      ADD CONSTRAINT fkovsacjon7ac5t8f8ey4k6bdjp FOREIGN KEY (tag_id)
      REFERENCES public.library_tags(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkp2kv8xfrruy4hikksh6ksvxs1'
  ) THEN
    ALTER TABLE public.catalogs
      ADD CONSTRAINT fkp2kv8xfrruy4hikksh6ksvxs1 FOREIGN KEY (last_updated_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkpaco7avm1ttddoqw3ng8hgxos'
  ) THEN
    ALTER TABLE public.component_definitions
      ADD CONSTRAINT fkpaco7avm1ttddoqw3ng8hgxos FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkq0jssk151g1kt9cx4vnomojc9'
  ) THEN
    ALTER TABLE public.invitations
      ADD CONSTRAINT fkq0jssk151g1kt9cx4vnomojc9 FOREIGN KEY (organization_id)
      REFERENCES public.organizations(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkqs3kns242tmtm6rrx1c44bibd'
  ) THEN
    ALTER TABLE public.artifact_versions
      ADD CONSTRAINT fkqs3kns242tmtm6rrx1c44bibd FOREIGN KEY (artifact_id)
      REFERENCES public.artifacts(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkskxms9unsl40y33c6sxkhr34r'
  ) THEN
    ALTER TABLE public.component_definitions
      ADD CONSTRAINT fkskxms9unsl40y33c6sxkhr34r FOREIGN KEY (last_updated_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkt8rd82twaiehek5d7p9y4ttm6'
  ) THEN
    ALTER TABLE public.oscal_documents
      ADD CONSTRAINT fkt8rd82twaiehek5d7p9y4ttm6 FOREIGN KEY (created_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fkt8wi5sbgymbqp7gobre09ujnr'
  ) THEN
    ALTER TABLE public.artifact_versions
      ADD CONSTRAINT fkt8wi5sbgymbqp7gobre09ujnr FOREIGN KEY (uploaded_by)
      REFERENCES public.users(id) ;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fku5csa0isw0cbaouceu9m39bp'
  ) THEN
    ALTER TABLE public.mfa_backup_codes
      ADD CONSTRAINT fku5csa0isw0cbaouceu9m39bp FOREIGN KEY (user_id)
      REFERENCES public.users(id) ;
  END IF;
END $$;
