-- Phase 2 of the registration-resilience plan:
--  1) self-serve forgot-password tokens
--  2) persisted email-send status on invitations so admins can see when the
--     invite email failed and use the copy-link / resend fallbacks

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    used_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_password_reset_tokens_hash
    ON password_reset_tokens (token_hash);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user
    ON password_reset_tokens (user_id);

ALTER TABLE invitations
    ADD COLUMN IF NOT EXISTS email_sent boolean NOT NULL DEFAULT false;
