--
-- Drift catch-up: AI tables that are present in V1.0__baseline.sql but
-- missing from production databases that never ran the original
-- V1.22__ai_features.sql (which was consolidated into V1.0 and removed).
--
-- Why this is needed
-- ------------------
-- V1.0__baseline.sql is a snapshot of a dev/staging DB that already had
-- V1.5..V1.22 applied. With baseline-on-migrate=true and baseline-version=1.0,
-- Flyway baselines an existing prod DB *at* V1.0 — i.e., it marks V1.0 as
-- "already applied" without actually running it, then applies V1.1+ from
-- there. That's correct only if prod's actual schema matches V1.0's content.
--
-- Production was running with ddl-auto=update through 2026-05-02 (image tag
-- `20260502-183443-phase2e`). Hibernate auto-created tables for whatever
-- entities existed in that older codebase, but never created the AI tables
-- (added 2026-05-03 in the Flyway era). When the new image boots with
-- ddl-auto=validate, it fails immediately with:
--     Schema validation: missing table [ai_sessions]
--
-- This migration creates the missing tables idempotently. It's a no-op on
-- dev/staging where V1.0 created them already.
--
-- If a future deploy reveals more drift (another `Schema validation: missing
-- table [X]` error), extend this migration (or add V1.12) with the same
-- pattern.

CREATE TABLE IF NOT EXISTS public.ai_sessions (
    id                uuid                            NOT NULL,
    ended_at          timestamp(6) without time zone,
    error_code        character varying(64),
    error_message     text,
    input_summary     text,
    mode              character varying(16)           NOT NULL,
    model             character varying(64)           NOT NULL,
    organization_id   bigint                          NOT NULL,
    started_at        timestamp(6) without time zone  NOT NULL,
    status            character varying(20)           NOT NULL,
    tokens_in         integer                         NOT NULL,
    tokens_out        integer                         NOT NULL,
    user_id           bigint                          NOT NULL,
    wizard_kind       character varying(32)           NOT NULL,
    events_json       text,
    cost_usd_micros   bigint              DEFAULT 0   NOT NULL,
    CONSTRAINT ai_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT ai_sessions_mode_check
        CHECK (((mode)::text = ANY (ARRAY[
            'STREAMING'::text, 'THOROUGH'::text]))),
    CONSTRAINT ai_sessions_status_check
        CHECK (((status)::text = ANY (ARRAY[
            'RUNNING'::text, 'AWAITING_INPUT'::text, 'COMPLETED'::text,
            'CANCELLED'::text, 'FAILED'::text]))),
    CONSTRAINT ai_sessions_wizard_kind_check
        CHECK (((wizard_kind)::text = ANY (ARRAY[
            'SMOKE'::text, 'CATALOG'::text, 'PROFILE'::text,
            'COMPONENT_DEF'::text, 'SSP'::text, 'POAM'::text,
            'BUILDER_ASSIST'::text])))
);

CREATE TABLE IF NOT EXISTS public.org_ai_settings (
    id                          bigint  GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    anthropic_key_encrypted     text,
    anthropic_key_fingerprint   character varying(32),
    created_at                  timestamp(6) without time zone            NOT NULL,
    default_model               character varying(64)                     NOT NULL,
    enabled                     boolean                                   NOT NULL,
    organization_id             bigint                                    NOT NULL,
    updated_at                  timestamp(6) without time zone,
    CONSTRAINT org_ai_settings_pkey PRIMARY KEY (id),
    CONSTRAINT org_ai_settings_organization_id_key UNIQUE (organization_id)
);
